import { v4 as uuidv4 } from 'uuid';
import type { DeliveryService } from './interfaces.js';
import type { ArtifactRepository } from '../repository/interfaces.js';

export interface ExportResult {
  content: string;
  contentType: string;
  fileName: string;
}

export class DefaultDeliveryService implements DeliveryService {
  constructor(private artifactRepo: ArtifactRepository) {}

  async exportArtifact(artifactId: string, medium: string, _destination: string): Promise<boolean> {
    const artifact = this.artifactRepo.findById(artifactId);
    if (!artifact) return false;

    // For Level 1, we support markdown passthrough and HTML-for-PDF
    // The actual export content is generated by getExportContent
    return true;
  }

  async getExportContent(artifactId: string, medium: string): Promise<ExportResult | null> {
    const artifact = this.artifactRepo.findById(artifactId);
    if (!artifact) return null;

    switch (medium) {
      case 'markdown':
        return {
          content: artifact.content,
          contentType: 'text/markdown',
          fileName: `artifact-${artifactId.slice(0, 8)}.md`,
        };
      case 'pdf':
      case 'google_doc':
        return {
          content: markdownToHtml(artifact.content),
          contentType: 'text/html',
          fileName: `artifact-${artifactId.slice(0, 8)}.html`,
        };
      default:
        return {
          content: artifact.content,
          contentType: 'text/plain',
          fileName: `artifact-${artifactId.slice(0, 8)}.txt`,
        };
    }
  }
}

function markdownToHtml(markdown: string): string {
  let html = markdown;

  // Convert headers
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

  // Convert bold
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

  // Convert italic
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Convert unordered lists
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>');

  // Convert paragraphs (simple: lines with content that aren't already HTML)
  html = html.replace(/^(?!<[h|l|u|o])((?!^\s*$).+)$/gm, '<p>$1</p>');

  // Wrap in basic HTML document
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>TeachAssist Export</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; line-height: 1.6; }
  h1, h2, h3 { color: #333; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
</style>
</head>
<body>${html}</body>
</html>`;
}
